#!/usr/bin/env bash
# Configures a custom http response header

# Updating Packages

sudo apt-get update -y
sudo apt-get install nginx -y

#creating an index page
echo "Hello World!" | sudo tee  /var/www/html/index.html

#Performing  a redirection

new_string="server_name _;\n\trewrite ^\/redirect_me google.com permanent;"
sudo sed -i "s/server_name _;/$new_string/" /etc/nginx/sites-enabled/default

echo "Ceci n'est pas une page" | sudo tee  /var/www/html/404.html

sudo sed -i "server_name _;/a add_header x-Served-By $hostname;"  /etc/nginx/sites-enabled/default

sudo nginx -t

sudo service nginx restart


