#!/usr/bin/env bash
# Installs HAproxy and configures it
apt-get update -y
apt-get install -y haproxy

CONF="\
frontend main
	bind *:80
	mode http
	default_backend web-server

backend web-server
	balance roundrobin
	server 235708-web-01 18.235.233.125:80 check
	server 235708-web-02 54.160.90.146:80 check
"

echo "$CONF" >> /etc/haproxy/haproxy.cfg
echo "ENABLED=1" >> /etc/default/haproxy
service haproxy start
